[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "highlighter", "debug"] }
rfd = "0.15.2"
tokio = { version = "1.43.0", features = ["fs", "macros", "rt-multi-thread"] }
